project:
  type: website
  render: 
    # we want index to render last, as it summarizes all the datasets
    - "data-*.ipynb"
    - "index.ipynb"
  resources:
    - "data/*.parquet"
    - "data/fake_utc/*.parquet"

jupyter: python3

website:
  title: "France Grid"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - text: Pipeline
        menu: 
          - text: Generation
          - href: data-generation-01-ingest.ipynb
            text: Ingest

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



