project:
  type: website
  resources:
    - "data/*.parquet"
    - "data/fake_utc/*.parquet"

jupyter: python3

execute: 
  freeze: true
  
website:
  title: "France Grid"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Pipeline
        menu: 
          - text: Generation
          - href: data-generation-01-ingest.qmd
            text: Ingest
          - href: data-generation-02-transform.qmd
            text: Transform

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



