project:
  type: website
  resources:
    - "data/03-publish/standard/*.parquet"
    - "data/03-publish/fake-utc/*.parquet"

jupyter: python3

execute: 
  freeze: true
  
website:
  title: "France Grid"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Pipeline
        menu: 
          - text: Generation
          - text: Ingest
            href: data-generation-01-ingest.qmd
          - text: Transform
            href: data-generation-02-transform.qmd 
          - text: Publish
            href: data-generation-03-publish.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



