project:
  type: website
  resources:
    - "data/99-publish/standard/*.parquet"
    - "data/99-publish/fake-utc/*.parquet"

jupyter: python3

execute: 
  freeze: true
  
website:
  title: "France Grid"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Pipeline
        menu: 
          - text: Generation
          - text: Ingest
            href: data-generation-01-ingest.qmd
          - text: Transform
            href: data-generation-02-transform.qmd 
          - text: Publish
            href: data-generation-99-publish.qmd
          - text: "---"
          - text: Flow
          - text: Ingest
            href: data-flow-01-ingest.qmd
          - text: Transform
            href: data-flow-02-transform.qmd 
          - text: Publish
            href: data-flow-99-publish.qmd  
      - text: About
        menu:
          - text: Overview
            href: about-overview.qmd
          - text: DVC
            href: about-dvc.qmd
          - text: Quarto
            href: about-quarto.qmd
          - text: Polars
            href: about-polars.qmd
          - text: Observable
            href: about-observable.qmd  
    right: 
      - icon: github
        href: https://github.com/ijlyttle/grid-france
        aria-label: GitHub repository


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



