stages:
  
  flow-ingest:
    cmd: quarto render data-flow-01-ingest.qmd
    params: 
      - dvc-params.yaml:
        - tz_local
    deps:
      - data-flow-01-ingest.qmd
    outs: 
      - data/01-ingest/flow.json:
          persist: true
    # this step has logic on whether it needs to call the API or not, 
    # we want to keep the json output in case there was no API call.      
    always_changed: true

  flow-transform:
    cmd: quarto render data-flow-02-transform.qmd
    params: 
      - dvc-params.yaml:
        - tz_local
    deps:
      - data/01-ingest/flow.json
      - data-flow-02-transform.qmd
    outs: 
      - data/02-transform/flow.parquet:
          persist: true

  flow-publish:
    # todo: why do I need to "sleep"?
    #  - ERROR: NotFound: No such file or directory (os error 2), stat '/Users/ijlyttle/repos/public/grid-france/index_files'
    cmd: sleep 1; quarto render data-flow-99-publish.qmd
    deps:
      - data/02-transform/flow.parquet
      - data-flow-99-publish.qmd
    outs: 
      - data/99-publish/standard/flow.parquet:
          persist: true     
      - data/99-publish/fake-utc/flow.parquet:
          persist: true
      - data/99-publish/flow-meta.json:
          persist: true

  generation-ingest:
    cmd: quarto render data-generation-01-ingest.qmd
    params: 
      - dvc-params.yaml:
        - tz_local
    deps:
      - data-generation-01-ingest.qmd
    outs: 
      - data/01-ingest/generation.json:
          persist: true
    # this step has logic on whether it needs to call the API or not, 
    # we want to keep the json output in case there was no API call.      
    always_changed: true

  generation-transform:
    cmd: quarto render data-generation-02-transform.qmd
    params: 
      - dvc-params.yaml:
        - tz_local
    deps:
      - data/01-ingest/generation.json
      - data-generation-02-transform.qmd
    outs: 
      - data/02-transform/generation.parquet:
          persist: true
    
  generation-publish:
    cmd: sleep 1; quarto render data-generation-99-publish.qmd
    deps:
      - data/02-transform/generation.parquet
      - data-generation-99-publish.qmd
    outs: 
      - data/99-publish/standard/generation.parquet:
          persist: true     
      - data/99-publish/fake-utc/generation.parquet:
          persist: true
      - data/99-publish/generation-meta.json:
          persist: true
    
  index:
    cmd: quarto render index.qmd
    deps:
      - data/99-publish/standard/flow.parquet
      - data/99-publish/fake-utc/flow.parquet
      - data/99-publish/standard/generation.parquet
      - data/99-publish/fake-utc/generation.parquet
      - index.qmd

