stages:
  
  generation-ingest:
    cmd: quarto render data-generation-01-ingest.qmd
    params: 
      - dvc-params.yaml:
        - tz_local
    deps:
      - data-generation-01-ingest.qmd
    outs: 
      - data/01-ingest/generation.json:
          persist: true
    # this step has logic on whether it needs to call the API or not, 
    # we want to keep the json output in case there was no API call.      
    always_changed: true

  generation-transform:
    cmd: quarto render data-generation-02-transform.qmd
    deps:
      - data/01-ingest/generation.json
      - data-generation-02-transform.qmd
    outs: 
      - data/02-transform/generation.parquet:
          persist: true
    
  generation-publish:
    cmd: quarto render data-generation-99-publish.qmd
    deps:
      - data/02-transform/generation.parquet
      - data-generation-99-publish.qmd
    outs: 
      - data/99-publish/standard/generation.parquet:
          persist: true     
      - data/99-publish/fake-utc/generation.parquet:
          persist: true
      - data/99-publish/generation-meta.json:
          persist: true
    
  index:
    cmd: quarto render index.qmd
    deps:
      - data/99-publish/standard/generation.parquet
      - data/99-publish/fake-utc/generation.parquet
      - index.qmd

